function createfigure(YMatrix1, YMatrix2, YMatrix3, YMatrix4, YMatrix5, YMatrix6)
%CREATEFIGURE(YMatrix1, YMatrix2, YMatrix3, YMatrix4, YMatrix5, YMatrix6)
%  YMATRIX1:  matrix of plot y data
%  YMATRIX2:  matrix of plot y data
%  YMATRIX3:  matrix of plot y data
%  YMATRIX4:  matrix of plot y data
%  YMATRIX5:  matrix of plot y data
%  YMATRIX6:  matrix of plot y data

%  Auto-generated by MATLAB on 22-Jul-2024 14:57:49

% Create figure
figure1 = figure('WindowState','maximized','Name','MP vs. MyoMotion');

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.709264705882353 0.334659090909091 0.215735294117647]);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(YMatrix1);
set(plot1(1),'DisplayName','data1','Color',[0 1 1]);
set(plot1(2),'DisplayName','data2','Color',[0 1 1]);
set(plot1(3),'DisplayName','data3','Color',[0 1 1]);
set(plot1(4),'DisplayName','data4','Color',[0 1 1]);
set(plot1(5),'DisplayName','data5','Color',[0 1 1]);
set(plot1(6),'DisplayName','data6','Color',[0 1 1]);
set(plot1(7),'DisplayName','data7','Color',[0 1 1]);
set(plot1(8),'DisplayName','data8','Color',[0 1 1]);
set(plot1(9),'DisplayName','data9','Color',[0 1 1]);
set(plot1(10),'DisplayName','data10','Color',[0 1 1]);
set(plot1(11),'DisplayName','data11','Color',[0 1 1]);
set(plot1(12),'DisplayName','data12','Color',[0 0 1]);
set(plot1(13),'DisplayName','data13','Color',[0 0 1]);
set(plot1(14),'DisplayName','data14','Color',[0 0 1]);
set(plot1(15),'DisplayName','data15','Color',[0 0 1]);
set(plot1(16),'DisplayName','data16','Color',[0 0 1]);
set(plot1(17),'DisplayName','data17','Color',[0 0 1]);
set(plot1(18),'DisplayName','data18','Color',[0 0 1]);
set(plot1(19),'DisplayName','data19','Color',[0 0 1]);
set(plot1(20),'DisplayName','data20','Color',[0 0 1]);
set(plot1(21),'DisplayName','data21','Color',[0 0 1]);
set(plot1(22),'DisplayName','data22','Color',[0 0 1]);
set(plot1(23),'DisplayName','data23','Color',[0 1 0]);
set(plot1(24),'DisplayName','data24','Color',[0 1 0]);
set(plot1(25),'DisplayName','data25','Color',[0 1 0]);
set(plot1(26),'DisplayName','data26','Color',[0 1 0]);
set(plot1(27),'DisplayName','data27','Color',[0 1 0]);
set(plot1(28),'DisplayName','data28','Color',[0 1 0]);
set(plot1(29),'DisplayName','data29','Color',[0 1 0]);
set(plot1(30),'DisplayName','data30','Color',[0 1 0]);
set(plot1(31),'DisplayName','data31','Color',[0 1 0]);
set(plot1(32),'DisplayName','data32','Color',[0 1 0]);
set(plot1(33),'DisplayName','data33','Color',[0 1 0]);
set(plot1(34),'DisplayName','data34','Color',[1 0 0]);
set(plot1(35),'DisplayName','data35','Color',[1 0 0]);
set(plot1(36),'DisplayName','data36','Color',[1 0 0]);
set(plot1(37),'DisplayName','data37','Color',[1 0 0]);
set(plot1(38),'DisplayName','data38','Color',[1 0 0]);
set(plot1(39),'DisplayName','data39','Color',[1 0 0]);
set(plot1(40),'DisplayName','data40','Color',[1 0 0]);
set(plot1(41),'DisplayName','data41','Color',[1 0 0]);
set(plot1(42),'DisplayName','data42','Color',[1 0 0]);
set(plot1(43),'DisplayName','data43','Color',[1 0 0]);
set(plot1(44),'DisplayName','data44','Color',[1 0 0]);
set(plot1(45),'DisplayName','data45','Color',[1 0 0]);

% Create light
light('Parent',axes1,...
    'Position',[-0.86575489763891 0.499843823204061 0.0249921911602031]);

% Create ylabel
ylabel({'Hip Flexion (deg)'});

% Create xlabel
xlabel({'Gait cycle (%)'});

% Create title
title({'Normalized Data Hip, Knee, Ankle'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-1.05059422750425 120.149405772496]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-30 30]);
grid(axes1,'on');
hold(axes1,'off');
% Create subplot
subplot1 = subplot(3,2,2,'Parent',figure1);
hold(subplot1,'on');

% Create multiple line objects using matrix input to plot
plot2 = plot(YMatrix2);
set(plot2(1),'Color',[0 1 1]);
set(plot2(2),'Color',[0 0 1]);
set(plot2(3),'Color',[0 1 0]);
set(plot2(4),'Color',[1 0 0]);

% Create ylabel
ylabel({''});

% Create xlabel
xlabel({'Gait cycle (%)'});

% Create title
title({'Normalized mean Data Hip, Knee, Ankle'});

grid(subplot1,'on');
hold(subplot1,'off');
% Create subplot
subplot2 = subplot(3,2,3,'Parent',figure1);
hold(subplot2,'on');

% Create multiple line objects using matrix input to plot
plot3 = plot(YMatrix3);
set(plot3(1),'Color',[0 1 1]);
set(plot3(2),'Color',[0 1 1]);
set(plot3(3),'Color',[0 1 1]);
set(plot3(4),'Color',[0 1 1]);
set(plot3(5),'Color',[0 1 1]);
set(plot3(6),'Color',[0 1 1]);
set(plot3(7),'Color',[0 1 1]);
set(plot3(8),'Color',[0 1 1]);
set(plot3(9),'Color',[0 1 1]);
set(plot3(10),'Color',[0 1 1]);
set(plot3(11),'Color',[0 1 1]);
set(plot3(12),'Color',[0 0 1]);
set(plot3(13),'Color',[0 0 1]);
set(plot3(14),'Color',[0 0 1]);
set(plot3(15),'Color',[0 0 1]);
set(plot3(16),'Color',[0 0 1]);
set(plot3(17),'Color',[0 0 1]);
set(plot3(18),'Color',[0 0 1]);
set(plot3(19),'Color',[0 0 1]);
set(plot3(20),'Color',[0 0 1]);
set(plot3(21),'Color',[0 0 1]);
set(plot3(22),'Color',[0 0 1]);
set(plot3(23),'Color',[0 1 0]);
set(plot3(24),'Color',[0 1 0]);
set(plot3(25),'Color',[0 1 0]);
set(plot3(26),'Color',[0 1 0]);
set(plot3(27),'Color',[0 1 0]);
set(plot3(28),'Color',[0 1 0]);
set(plot3(29),'Color',[0 1 0]);
set(plot3(30),'Color',[0 1 0]);
set(plot3(31),'Color',[0 1 0]);
set(plot3(32),'Color',[0 1 0]);
set(plot3(33),'Color',[0 1 0]);
set(plot3(34),'Color',[1 0 0]);
set(plot3(35),'Color',[1 0 0]);
set(plot3(36),'Color',[1 0 0]);
set(plot3(37),'Color',[1 0 0]);
set(plot3(38),'Color',[1 0 0]);
set(plot3(39),'Color',[1 0 0]);
set(plot3(40),'Color',[1 0 0]);
set(plot3(41),'Color',[1 0 0]);
set(plot3(42),'Color',[1 0 0]);
set(plot3(43),'Color',[1 0 0]);
set(plot3(44),'Color',[1 0 0]);
set(plot3(45),'Color',[1 0 0]);

% Create ylabel
ylabel({'Knee Flexion (deg)'});

% Create xlabel
xlabel({'Gait cycle (%)'});

grid(subplot2,'on');
hold(subplot2,'off');
% Create subplot
subplot3 = subplot(3,2,4,'Parent',figure1);
hold(subplot3,'on');

% Create multiple line objects using matrix input to plot
plot4 = plot(YMatrix4);
set(plot4(1),'Color',[0 1 1]);
set(plot4(2),'Color',[0 0 1]);
set(plot4(3),'Color',[0 1 0]);
set(plot4(4),'Color',[1 0 0]);

% Create light
light('Parent',subplot3,...
    'Position',[-0.783853103772574 0.620533875222933 0.022627890023411]);

% Create xlabel
xlabel({'Gait cycle (%)'});

grid(subplot3,'on');
hold(subplot3,'off');
% Create subplot
subplot4 = subplot(3,2,5,'Parent',figure1);
hold(subplot4,'on');

% Create multiple line objects using matrix input to plot
plot5 = plot(YMatrix5);
set(plot5(1),'Color',[0 1 1]);
set(plot5(2),'Color',[0 1 1]);
set(plot5(3),'Color',[0 1 1]);
set(plot5(4),'Color',[0 1 1]);
set(plot5(5),'Color',[0 1 1]);
set(plot5(6),'Color',[0 1 1]);
set(plot5(7),'Color',[0 1 1]);
set(plot5(8),'Color',[0 1 1]);
set(plot5(9),'Color',[0 1 1]);
set(plot5(10),'Color',[0 1 1]);
set(plot5(11),'Color',[0 1 1]);
set(plot5(12),'Color',[0 0 1]);
set(plot5(13),'Color',[0 0 1]);
set(plot5(14),'Color',[0 0 1]);
set(plot5(15),'Color',[0 0 1]);
set(plot5(16),'Color',[0 0 1]);
set(plot5(17),'Color',[0 0 1]);
set(plot5(18),'Color',[0 0 1]);
set(plot5(19),'Color',[0 0 1]);
set(plot5(20),'Color',[0 0 1]);
set(plot5(21),'Color',[0 0 1]);
set(plot5(22),'Color',[0 0 1]);
set(plot5(23),'Color',[0 1 0]);
set(plot5(24),'Color',[0 1 0]);
set(plot5(25),'Color',[0 1 0]);
set(plot5(26),'Color',[0 1 0]);
set(plot5(27),'Color',[0 1 0]);
set(plot5(28),'Color',[0 1 0]);
set(plot5(29),'Color',[0 1 0]);
set(plot5(30),'Color',[0 1 0]);
set(plot5(31),'Color',[0 1 0]);
set(plot5(32),'Color',[0 1 0]);
set(plot5(33),'Color',[0 1 0]);
set(plot5(34),'Color',[1 0 0]);
set(plot5(35),'Color',[1 0 0]);
set(plot5(36),'Color',[1 0 0]);
set(plot5(37),'Color',[1 0 0]);
set(plot5(38),'Color',[1 0 0]);
set(plot5(39),'Color',[1 0 0]);
set(plot5(40),'Color',[1 0 0]);
set(plot5(41),'Color',[1 0 0]);
set(plot5(42),'Color',[1 0 0]);
set(plot5(43),'Color',[1 0 0]);
set(plot5(44),'Color',[1 0 0]);
set(plot5(45),'Color',[1 0 0]);

% Create ylabel
ylabel({'Ankle Flexion (deg)'});

% Create xlabel
xlabel({'Gait cycle (%)'});

grid(subplot4,'on');
hold(subplot4,'off');
% Create subplot
subplot5 = subplot(3,2,6,'Parent',figure1);
hold(subplot5,'on');

% Create multiple line objects using matrix input to plot
plot6 = plot(YMatrix6);
set(plot6(1),'DisplayName','light','Color',[0 1 1]);
set(plot6(2),'DisplayName','mm','Color',[0 0 1]);
set(plot6(3),'DisplayName','moderate','Color',[0 1 0]);
set(plot6(4),'DisplayName','off','Color',[1 0 0]);

% Create xlabel
xlabel({'Gait cycle (%)'});

grid(subplot5,'on');
hold(subplot5,'off');
% Create legend
legend1 = legend(subplot5,'show');
set(legend1,...
    'Position',[0.437321243924776 0.645779844539382 0.162083334664504 0.0207296853041767],...
    'Orientation','horizontal');

